version: '3.8'

services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: journal_db

  patientapi:
    build:
      context: ./PatientApi
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/journal_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db

  messageapi:
    build:
      context: ./MessagesApi
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/journal_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db
      - patientapi

  userapi:
    build:
      context: ./UserApi
    ports:
      - "8083:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/journal_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db
      - patientapi

  frontend:
    build: ./JournalReact2
    ports:
      - "5000:80" # Map port 5000 on the host to port 80 in the container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # Optional: Mount Nginx config for live changes
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - patientapi
      - messageapi
      - userapi



volumes:
  journal_data:
